//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBusiness.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PGStayBusinessEntities : DbContext
    {
        public PGStayBusinessEntities()
            : base("name=PGStayBusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_pgdb_users_info> tbl_pgdb_users_info { get; set; }
        public virtual DbSet<tbl_pgsb_code_values> tbl_pgsb_code_values { get; set; }
        public virtual DbSet<tbl_pgsb_log> tbl_pgsb_log { get; set; }
        public virtual DbSet<tbl_pgsb_paying_guest_homestay> tbl_pgsb_paying_guest_homestay { get; set; }
        public virtual DbSet<tbl_pgsb_pg_amenities> tbl_pgsb_pg_amenities { get; set; }
        public virtual DbSet<tbl_pgsb_pg_homestay_images> tbl_pgsb_pg_homestay_images { get; set; }
        public virtual DbSet<tbl_pgsb_users> tbl_pgsb_users { get; set; }
        public virtual DbSet<tbl_pgsb_pg_sharing_classification> tbl_pgsb_pg_sharing_classification { get; set; }
    }
}
