//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBusiness.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pgsb_pg_homestay_images
    {
        public decimal pg_image_id { get; set; }
        public string pg_id { get; set; }
        public string image_fullpath { get; set; }
        public string image_name { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public byte delete_ind { get; set; }
        public byte active_ind { get; set; }
    
        public virtual tbl_pgsb_paying_guest_homestay tbl_pgsb_paying_guest_homestay { get; set; }
    }
}
