//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBusiness.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pgdb_users_info
    {
        public decimal user_info_id { get; set; }
        public string user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string full_name { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public Nullable<decimal> pin_code { get; set; }
        public string phone_number { get; set; }
        public string emailId { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public Nullable<System.DateTime> modifed_date { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public byte delete_ind { get; set; }
        public byte active_ind { get; set; }
        public byte modified_ind { get; set; }
        public Nullable<int> area_code { get; set; }
    
        public virtual tbl_pgsb_users tbl_pgsb_users { get; set; }
    }
}
