//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBusiness.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pgsb_paying_guest_homestay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pgsb_paying_guest_homestay()
        {
            this.tbl_pgsb_pg_amenities = new HashSet<tbl_pgsb_pg_amenities>();
            this.tbl_pgsb_pg_homestay_images = new HashSet<tbl_pgsb_pg_homestay_images>();
            this.tbl_pgsb_pg_sharing_classification = new HashSet<tbl_pgsb_pg_sharing_classification>();
        }
    
        public string pg_id { get; set; }
        public string name { get; set; }
        public string owner_name { get; set; }
        public string incharge_id { get; set; }
        public string incharge_person_details { get; set; }
        public string contact_phone_number { get; set; }
        public string email_id { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public int pin_code { get; set; }
        public int area_code { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public byte delete_ind { get; set; }
        public byte active_ind { get; set; }
        public Nullable<byte> modified_ind { get; set; }
        public int pg_type_code { get; set; }
    
        public virtual tbl_pgsb_users tbl_pgsb_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pgsb_pg_amenities> tbl_pgsb_pg_amenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pgsb_pg_homestay_images> tbl_pgsb_pg_homestay_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pgsb_pg_sharing_classification> tbl_pgsb_pg_sharing_classification { get; set; }
    }
}
