//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBusiness.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pgsb_log
    {
        public decimal id { get; set; }
        public string log_data { get; set; }
        public string logged_user_information { get; set; }
        public Nullable<decimal> login_id { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
